apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sync-server.yaml
  - sync-server-service.yaml
  - sync-server-service-account.yaml
  - redis-service.yaml
  - redis.yaml

configMapGenerator:
  - files:
      - config.yml
    name: sync-server-config

secretGenerator:
  - literals:
      - REDIS_USERNAME=
      - REDIS_PASSWORD=redis
    name: sync-server-secret

vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: REDIS_NAMESPACE
    objref:
      apiVersion: v1
      kind: Service
      name: redis
  - fieldref:
      fieldPath: metadata.name
    name: REDIS_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: redis
  - fieldref:
      fieldPath: spec.template.spec.containers[0].ports.[0].containerPort
    name: REDIS_PORT
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: redis

namePrefix: octi-
namespace: octi-system

images:
  - name: ghcr.io/jakobmoellerdev/octi-sync-server.yaml
    newTag: latest
  - name: redis
    newTag: 7.0.4
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/created-by: kustomize
      app.kubernetes.io/instance: main
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: octi
