// Package REST provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package REST

const (
	DeviceAuthScopes = "deviceAuth.Scopes"
)

// Defines values for HealthResult.
const (
	Down HealthResult = "Down"
	Up   HealthResult = "Up"
)

// HealthAggregation defines model for HealthAggregation.
type HealthAggregation struct {
	// The different Components of the Server
	Components *[]HealthAggregationComponent `json:"components,omitempty"`

	// A Health Check Result
	Health HealthResult `json:"health"`
}

// HealthAggregationComponent defines model for HealthAggregationComponent.
type HealthAggregationComponent struct {
	// A Health Check Result
	Health HealthResult `json:"health"`

	// The Name of the Component to be Health Checked
	Name string `json:"name"`
}

// A Health Check Result
type HealthResult string

// Module Data Stream
type ModuleDataStream = map[string]interface{}

// Module Name
type ModuleName = string

// RegistrationResponse defines model for RegistrationResponse.
type RegistrationResponse struct {
	DeviceID string `json:"deviceID"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// ShareResponse defines model for ShareResponse.
type ShareResponse struct {
	ShareCode *string `json:"shareCode,omitempty"`
}

// ShareCode defines model for ShareCode.
type ShareCode = string

// XDeviceID defines model for XDeviceID.
type XDeviceID = string

// An Empty JSON
type ModuleDataAccepted = interface{}

// RegisterParams defines parameters for Register.
type RegisterParams struct {
	// The Device ID for Registration
	XDeviceID XDeviceID `json:"X-Device-ID"`
}

// ShareParams defines parameters for Share.
type ShareParams struct {
	// The Device ID for Registration
	XDeviceID XDeviceID `json:"X-Device-ID"`
}

// GetModuleParams defines parameters for GetModule.
type GetModuleParams struct {
	// The Share Code for Registration
	Share *ShareCode `form:"share,omitempty" json:"share,omitempty"`

	// The Device ID for Registration
	XDeviceID XDeviceID `json:"X-Device-ID"`
}

// CreateModuleParams defines parameters for CreateModule.
type CreateModuleParams struct {
	// The Share Code for Registration
	Share *ShareCode `form:"share,omitempty" json:"share,omitempty"`

	// The Device ID for Registration
	XDeviceID XDeviceID `json:"X-Device-ID"`
}
