// Code generated by MockGen. DO NOT EDIT.
// Source: accounts.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/jakob-moeller-cloud/octi-sync-server/service"
)

// MockAccounts is a mock of Accounts interface.
type MockAccounts struct {
	ctrl     *gomock.Controller
	recorder *MockAccountsMockRecorder
}

// MockAccountsMockRecorder is the mock recorder for MockAccounts.
type MockAccountsMockRecorder struct {
	mock *MockAccounts
}

// NewMockAccounts creates a new mock instance.
func NewMockAccounts(ctrl *gomock.Controller) *MockAccounts {
	mock := &MockAccounts{ctrl: ctrl}
	mock.recorder = &MockAccountsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccounts) EXPECT() *MockAccountsMockRecorder {
	return m.recorder
}

// ActiveShares mocks base method.
func (m *MockAccounts) ActiveShares(ctx context.Context, username string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActiveShares", ctx, username)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActiveShares indicates an expected call of ActiveShares.
func (mr *MockAccountsMockRecorder) ActiveShares(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActiveShares", reflect.TypeOf((*MockAccounts)(nil).ActiveShares), ctx, username)
}

// Find mocks base method.
func (m *MockAccounts) Find(ctx context.Context, username string) (service.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, username)
	ret0, _ := ret[0].(service.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockAccountsMockRecorder) Find(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockAccounts)(nil).Find), ctx, username)
}

// HealthCheck mocks base method.
func (m *MockAccounts) HealthCheck() service.HealthCheck {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheck")
	ret0, _ := ret[0].(service.HealthCheck)
	return ret0
}

// HealthCheck indicates an expected call of HealthCheck.
func (mr *MockAccountsMockRecorder) HealthCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheck", reflect.TypeOf((*MockAccounts)(nil).HealthCheck))
}

// IsShared mocks base method.
func (m *MockAccounts) IsShared(ctx context.Context, username, share string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsShared", ctx, username, share)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsShared indicates an expected call of IsShared.
func (mr *MockAccountsMockRecorder) IsShared(ctx, username, share interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsShared", reflect.TypeOf((*MockAccounts)(nil).IsShared), ctx, username, share)
}

// Register mocks base method.
func (m *MockAccounts) Register(ctx context.Context, username, password string) (service.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, password)
	ret0, _ := ret[0].(service.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAccountsMockRecorder) Register(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAccounts)(nil).Register), ctx, username, password)
}

// Revoke mocks base method.
func (m *MockAccounts) Revoke(ctx context.Context, username, shareCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, username, shareCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockAccountsMockRecorder) Revoke(ctx, username, shareCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockAccounts)(nil).Revoke), ctx, username, shareCode)
}

// Share mocks base method.
func (m *MockAccounts) Share(ctx context.Context, username string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Share", ctx, username)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Share indicates an expected call of Share.
func (mr *MockAccountsMockRecorder) Share(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Share", reflect.TypeOf((*MockAccounts)(nil).Share), ctx, username)
}
