// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "jakob-moeller.de",
            "email": "contact@jakob-moeller.de"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://github.com/jakob-moeller-cloud/octi-sync-server/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Creates a new Registration",
                "tags": [
                    "auth"
                ],
                "summary": "register Device Registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device Header",
                        "name": "X-Device-ID",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "413": {
                        "description": "Request Entity Too Large"
                    },
                    "429": {
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/module/{name}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the Module",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "getModule Get the Module",
                "parameters": [
                    {
                        "type": "string",
                        "description": "module-name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Device Header",
                        "name": "X-Device-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "413": {
                        "description": "Request Entity Too Large"
                    },
                    "429": {
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Create the Module",
                "consumes": [
                    "application/octet-stream"
                ],
                "tags": [
                    "modules"
                ],
                "summary": "createModule Create the Module",
                "parameters": [
                    {
                        "type": "string",
                        "description": "module-name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "module-name",
                        "name": "moduleData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Device Header",
                        "name": "X-Device-ID",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "413": {
                        "description": "Request Entity Too Large"
                    },
                    "429": {
                        "description": "Too Many Requests"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "generated",
	Host:             "localhost:8080",
	BasePath:         "/v1/swagger",
	Schemes:          []string{},
	Title:            "Octi Sync Server",
	Description:      "This is the Octi Sync Server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
